version: '2'
services:
    jhipstermonolithapplication-app:
        image: jhipstermonolithapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermonolithapplication-mysql:3306/jhipstermonolithapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 18082:18082
    jhipstermonolithapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstermonolithapplication-mysql
